//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace GenEntityConfigTypes {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/EntityConfig.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/EntityConfig.xsd", IsNullable=false)]
    public partial class Entity {
        
        private string nameField;
        
        private string descriptionField;
        
        private string typeField;
        
        private PartList partsField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public PartList Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/EntityConfig.xsd")]
    public partial class PartList {
        
        private Part partField;
        
        /// <remarks/>
        public Part Part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/EntityConfig.xsd")]
    public partial class Part {
        
        private string nameField;
        
        private Model modelField;
        
        private Body bodyField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Model Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public Body Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/EntityConfig.xsd")]
    public partial class Model {
        
        private string relFilepathField;
        
        private Vector3D relTranslationField;
        
        private Vector3D relRotationField;
        
        /// <remarks/>
        public string relFilepath {
            get {
                return this.relFilepathField;
            }
            set {
                this.relFilepathField = value;
            }
        }
        
        /// <remarks/>
        public Vector3D relTranslation {
            get {
                return this.relTranslationField;
            }
            set {
                this.relTranslationField = value;
            }
        }
        
        /// <remarks/>
        public Vector3D relRotation {
            get {
                return this.relRotationField;
            }
            set {
                this.relRotationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/EntityConfig.xsd")]
    public partial class Vector3D {
        
        private decimal xField;
        
        private decimal yField;
        
        private decimal zField;
        
        public Vector3D() {
            this.xField = ((decimal)(0m));
            this.yField = ((decimal)(0m));
            this.zField = ((decimal)(0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
        public decimal X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
        public decimal Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
        public decimal Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/EntityConfig.xsd")]
    public partial class Triangle {
        
        private Vector3D centerField;
        
        private Vector3D point1Field;
        
        private Vector3D point2Field;
        
        private Vector3D point3Field;
        
        /// <remarks/>
        public Vector3D Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        public Vector3D Point1 {
            get {
                return this.point1Field;
            }
            set {
                this.point1Field = value;
            }
        }
        
        /// <remarks/>
        public Vector3D Point2 {
            get {
                return this.point2Field;
            }
            set {
                this.point2Field = value;
            }
        }
        
        /// <remarks/>
        public Vector3D Point3 {
            get {
                return this.point3Field;
            }
            set {
                this.point3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/EntityConfig.xsd")]
    public partial class Box {
        
        private Vector3D centerField;
        
        private Vector3D sideLengthsField;
        
        /// <remarks/>
        public Vector3D Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        public Vector3D SideLengths {
            get {
                return this.sideLengthsField;
            }
            set {
                this.sideLengthsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/EntityConfig.xsd")]
    public partial class Primitive {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Box", typeof(Box))]
        [System.Xml.Serialization.XmlElementAttribute("Triangle", typeof(Triangle))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/EntityConfig.xsd")]
    public partial class Body {
        
        private Vector3D relTranslationField;
        
        private Vector3D relRotationField;
        
        private Primitive[] skinField;
        
        /// <remarks/>
        public Vector3D relTranslation {
            get {
                return this.relTranslationField;
            }
            set {
                this.relTranslationField = value;
            }
        }
        
        /// <remarks/>
        public Vector3D relRotation {
            get {
                return this.relRotationField;
            }
            set {
                this.relRotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Primitive[] Skin {
            get {
                return this.skinField;
            }
            set {
                this.skinField = value;
            }
        }
    }
}
